using System;
using System.Collections.Generic;
using System.Text;

namespace Traducteur_FrancoJaponais.Constants
{
    public static class TagCss
    {
        public static List<String> Orthographe = new List<string>()
        {
            "&#x27;ku&#x27; adjective (archaic)",
            "&#x27;shiku&#x27; adjective (archaic)",
            "adjective (generic)",
            "adverb",
            "adverb taking the と particle",
            "archaic/formal form of na-adjective",
            "auxiliary",
            "auxiliary adjective",
            "auxiliary verb",
            "conjunction",
            "copula",
            "female term",
            "godan verb",
            "godan verb (archaic)",
            "grammar",
            "ichidan verb",
            "interjection",
            "intransitive verb",
            "irregular nu verb",
            "irregular okurigana",
            "irregular ru verb",
            "kuru verb",
            "male term",
            "nidan verb (archaic)",
            "noun",
            "noun (generic)",
            "noun (prefix)",
            "noun (suffix)",
            "noun or participle taking the aux. verb する",
            "noun or verb acting prenominally",
            "noun taking the genitive case particle の",
            "particle",
            "prefix",
            "pre-noun adjectival",
            "pronoun",
            "su verb - precursor to the modern suru",
            "suffix",
            "suru verb",
            "transitive verb",
            "unclassified",
            "unclassified name",
            "verb (generic)",
            "yodan verb (archaic)",
            "い adjective",
            "たる adjective",
            "な adjective",
        };
        public static List<String> Domaine = new List<string>()
        {
            "agriculture",
            "anatomy",
            "archeology",
            "architecture",
            "art, aesthetics",
            "astronomy",
            "audiovisual",
            "aviation",
            "baseball",
            "biochemistry",
            "biology",
            "botany",
            "boxing",
            "Buddhism",
            "business",
            "card games",
            "chemistry",
            "chinese mythology",
            "christianity",
            "civil engineering",
            "clothing",
            "company name",
            "computing",
            "creature",
            "crystallography",
            "deity",
            "dentistry",
            "ecology",
            "economics",
            "electricity, elec. eng.",
            "electronics",
            "engineering",
            "entomology",
            "event",
            "fiction",
            "figure skating",
            "film",
            "finance",
            "fishing",
            "food, cooking",
            "gardening, horticulture",
            "genetics",
            "geography",
            "geology",
            "geometry",
            "go (game)",
            "golf",
            "greek mythology",
            "historical term",
            "horse racing",
            "internet",
            "japanese mythology",
            "kabuki",
            "law",
            "legend",
            "linguistics",
            "logic",
            "mahjong",
            "manga",
            "martial arts",
            "mathematics",
            "mechanical engineering",
            "medicine",
            "meteorology",
            "military",
            "mineralogy",
            "mining",
            "motorsport",
            "music",
            "mythology",
            "ornithology",
            "pharmacology",
            "philosophy",
            "photography",
            "physics",
            "physiology",
            "politics",
            "printing",
            "professional wrestling",
            "psychiatry",
            "psychoanalysis",
            "psychology",
            "railway",
            "roman mythology",
            "shinto",
            "skiing",
            "sports",
            "statistics",
            "stock market",
            "sumo",
            "surgery",
            "telecommunications",
            "television",
            "trademark",
            "veterinary terms",
            "video games",
            "zoology",
        };

        public static List<String> Origines = new List<string>()
        {
            "ainu origin",
            "ancient Greek origin",
            "arabic origin",
            "brazilian",
            "burmese origin",
            "chinese origin",
            "czech origin",
            "danish origin",
            "dutch origin",
            "english origin",
            "finnish origin",
            "french origin",
            "gairaigo",
            "german origin",
            "hawaiian origin",
            "hindi origin",
            "italian origin",
            "korean origin",
            "latin origin",
            "malay origin",
            "manchu origin",
            "modern Greek origin",
            "mongolian origin",
            "norwegian origin",
            "portuguese origin",
            "russian origin",
            "sanskrit origin",
            "spanish origin",
            "swedish origin",
            "tagalog origin",
            "tahitian origin",
            "thai origin",
            "tibetan origin",
            "turkish origin",
            "uzbek origin",
            "vietnamese origin",
            "yiddish origin",
        };
        public static List<String> JLPT = new List<string>()
        {
            "jlpt n1",
            "jlpt n2",
            "jlpt n3",
            "jlpt n4",
            "jlpt n5",
        };
    }
}
